version: '3'
services:
  frontend:
    build:
      context: .  # Path to the frontend folder
      dockerfile: frontend/Dockerfile  # Name of the Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8000
    depends_on:
      - backend

  backend:
    build:
      context: ./backend  # Path to the backend folder
      dockerfile: Dockerfile  # Name of the Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/static:/app/static
      - ./backend/temp_audio:/app/temp_audio